robot_name: 'go2'

state_publisher:
  update_rate: 400 # Hz

static_controller:
  stand_controller:
    joint_angles: [0.0, 0.806, -1.802, 0.0, 0.996, -1.802, 0.0, 0.806, -1.802, 0.0, 0.996, -1.802] # LF, LH, RF, RH
  sit_controller:
    joint_angles: [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65] # LF, LH, RF, RH
  kp: 90
  kd: 0.5
  interpolation_time: 1.0 # s
  rate: 50 # Hz

bob_controller:
  blind: true
  kp: 30.0
  kd: 0.5

  hf_repo: "kubjonai/tbai-models"
  hf_model: "go2_blind_no_vel_noise.pt"
  
  action_scale: 0.25
  lin_vel_scale: 2.0

  default_stance: [
    [ 0.025,  0.096, -0.263],
    [-0.025,  0.096, -0.263],
    [ 0.025, -0.096, -0.263],
    [-0.025, -0.096, -0.263],
  ]

  ik:
    d2: 0.0955
    a3: 0.213
    a4: 0.213

  cpg:
    period: 0.6
    time_offsets: [0.0, 0.3, 0.3, 0.0]  # LF, LH, RF, RH
    swing_height: 0.1

np3o:
  kp: 40.0
  kd: 1.0
  use_action_filter: true
  hf_repo: "kubjonai/tbai-models"
  hf_model: "np3o_model_1_original.pt"